# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [ipinc, alexandresaiz, mouse3687]
patreon: # Replace with a single Patreon username https://www.patreon.com/posts/22854182
open_collective: # Replace with a single Open Collective username https://www.beachbody.com/
ko_fi: # Replace with a single Ko-fi Mario 
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay opensea.io
issuehunt: # Replace with a single IssueHunt username ironsource.io 
otechie: # Replace with a single Otechie username zack 
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://Masterclass.com', 'https://Cspire.com, https://xboxlive.com']
https://chime.com
https://app.hunterz.io/wizard
