# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [mouse3687, nogo, Victoria, enterprise]
patreon: # Replace with a single Patreon username https://www.patreon.com/posts/22854182
open_collective: # Replace with a single Open https://event.on24.com/eventRegistration/EventLobbyServlet?target=reg30.jsp&referrer=https%3A%2F%2Freg.sapinsideronline.com%2Freg%2F2048%2F1731%2Fgoogle%2F&eventid=2190067&sessionid=1&key=B4088601ECD5362899B0B28DBF12608F&regTag=&sourcepage=register
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm i @babel/runtime
community_bridge: # Replace with a single Community Bridge project-name e.g., stone-foundry, Tor.onion, https://developer.ibm.com/solutions/mobile-app-development/
liberapay: # Replace with a single Liberapay username calm
issuehunt: # Replace with a single IssueHunt username noom
otechie: # Replace with a single Otechie username handy
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://NSA.gov', 'https://goarmy.com']

https://positivepest.com
https://Foe.tv
